# QM35 core apis module
qm35_apis-y := \
		qm35_bypass.o \
		qm35_core.o \
		qm35_ids.o \
		qm35_notifier.o \
		qm35_transport.o \
		qm35_trc.o

obj-m += qm35_apis.o

# QM35 UCI char device
qm35_uci_dev-y :=\
		qm35_uci_dev_main.o \
		qm35_uci_dev_trc.o

obj-m += qm35_uci_dev.o

# QM35 Log module
obj-m += qm35_logs.o

# QM35 coredump extractor
obj-m += qm35_coredump.o

# Optional QM35 HWSIM
obj-$(CONFIG_QM35_HWSIM) += hwsim/

