DLKM_DIR := motorola/kernel/modules
LOCAL_PATH := $(call my-dir)

ifeq ($(AW96XX_USB_USE_ONLINE),true)
	KERNEL_CFLAGS += CONFIG_AW96XX_POWER_SUPPLY_ONLINE=y
	KBUILD_OPTIONS += CONFIG_AW96XX_POWER_SUPPLY_ONLINE=y
endif

<<<<<<< HEAD
=======
ifeq ($(PHONE_CASE_SUPPORT),true)
    KBUILD_OPTIONS += CONFIG_CAPSENSE_HALL_CAL=y
endif

>>>>>>> e7041f1203 (sx937x&awinic mag shell cal)
include $(CLEAR_VARS)
LOCAL_MODULE := awinic_sar.ko
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(KERNEL_MODULES_OUT)
LOCAL_ADDITIONAL_DEPENDENCIES := $(KERNEL_MODULES_OUT)/sensors_class.ko
ifeq ($(PHONE_CASE_SUPPORT),true)
    LOCAL_ADDITIONAL_DEPENDENCIES += $(KERNEL_MODULES_OUT)/hall_phone_case.ko
endif
#LOCAL_REQUIRED_MODULES := sensors_class.ko
KBUILD_OPTIONS_GKI += GKI_OBJ_MODULE_DIR=gki
KBUILD_OPTIONS += MODULE_KERNEL_VERSION=$(TARGET_KERNEL_VERSION)
include $(DLKM_DIR)/AndroidKernelModule.mk

